version: '3.0'

services:
  database:
    container_name: apollo-db
    image: 'postgres:12.10'
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
